### ISSUE TITLE
could I get process open fd through taskstats

### ISSUE THREAD

**Issue by liuyangc3** [facebook/gnlpy#11]
it can be found in /proc/`<pid>`/fd

dose taskstats support it? I checked taskstats  ,seems not in fields
```
__fields__ = [
        'version', 'exitcode', 'flag', 'nice', 'cpu_count',
        'cpu_delay_total', 'blkio_count', 'blkio_delay_total',
        'swapin_count', 'swapin_delay_total',
        'cpu_run_real_total', 'cpu_run_virtual_total', 'comm',
        'sched', 'uid', 'gid', 'pid', 'ppid', 'btime', 'etime',
        'utime', 'stime', 'minflt', 'majflt', 'coremem',
        'virtmem', 'hiwater_rss', 'hiwater_vm', 'read_char',
        'write_char', 'read_syscalls', 'write_syscalls',
        'read_bytes', 'write_bytes', 'cancelled_write_bytes',
        'nvcsw', 'nivcsw', 'utimescaled', 'stimescaled',
        'cpu_scaled_run_real_total', 'freepages_count',
        'freepages_delay_total'
    ]
```
sorry I know this has nothing to do with gnlpy. but I am really not  familiar with taskstats and netlink.

**Comment by chantra** [comment]
@liuyangc3 
It does not seem taskstats exposes the file descriptors: http://lxr.free-electrons.com/source/include/uapi/linux/taskstats.h

so gnlpy won't be able to provide this information at this time.

I will be closing this issue for now given that the info is not readily available from the kernel.
