### ISSUE TITLE
Upload to pip

### ISSUE THREAD

**Issue by lavagetto** [facebook/gnlpy#7]
It would be awesome to be able to install gnlpy via pip, that would help production installations wherever pip is allowed, or just unit testing/ci for projects that do use gnlpy. I think that's a better alternative compared to using git submodules, which is what I am going to do at the moment if gnlpy is not uploaded to pip

**Comment by chantra** [comment]
Based on current master: https://pypi.python.org/pypi/gnlpy

**Comment by lavagetto** [comment]
@chantra @vmauge thanks!
